version: 2
jobs:
  sbt:
    docker:
      - image: nwtgck/pre-installed-sbt:1.0.2
    steps:
      - checkout
      - run: sbt compile
      # Working test
      - run: 'sbt "runMain io.github.nwtgck.svg_badge.Main build passing #6c3"'
      - run: cat ./build-passing.svg

workflows:
  version: 2
  build:
    jobs:
      - sbt
